### ISSUE TITLE
Doesn't work with Python >3.7

### ISSUE THREAD

**Issue by egerlach** [gappleto97/overpassify#29]
Starting in Python 3.8, it appears the internal AST implementation changed. This is the error I get importing from python 3.8 onwards:

```
(overpass) debian@debian:~/overpass$ python --version
Python 3.8.20
(overpass) debian@debian:~/overpass$ python -c 'import overpassify'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/debian/overpass/.venv/lib/python3.8/site-packages/overpassify/__init__.py", line 1, in <module>
    from .overpassify import (overpassify, parse)
  File "/home/debian/overpass/.venv/lib/python3.8/site-packages/overpassify/overpassify.py", line 350, in <module>
    @parse.register(_ast.Str)
AttributeError: module '_ast' has no attribute 'Str'
```
